### ISSUE TITLE
Is this for stable or experimental?

### ISSUE THREAD

**Issue by Holli-Git** [Megamimed/Cataclysm-DDA-FORBIDDEN_MODS#1]
I've noticed a few things like the FS2K still having a damage malus, despite that now being handled by barrel length and ammo in experimental. I'm up for PRing fixes, just want to know for what version of the game this is, thank you!

**Comment by Megamimed** [comment]
I'm trying to keep it up to date with experimental, I'll add that to the readme thanks!
